insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Zbigniew', 'Opiekuńczy', '00-100 Opiekunowo ul. Opiekunów 62');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Samuel', 'Ray', '618 Orin Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Catherine', 'Ryan', '47 Clove Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Christopher', 'Greene', '127 Blue Bill Park Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Tina', 'Castillo', '38 Eagan Center');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Paul', 'Kelly', '342 Corscot Park');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Judy', 'Wells', '731 Lakewood Gardens Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Russell', 'Nichols', '15 Carey Place');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kevin', 'Day', '81 Anthes Road');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Linda', 'Moore', '5 Starling Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Lisa', 'Stevens', '3343 Bonner Trail');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Rose', 'Gibson', '835 Chinook Avenue');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Sara', 'Greene', '094 Bunker Hill Point');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Dennis', 'Nichols', '0322 Vidon Hill');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Gloria', 'Carr', '0599 Sauthoff Road');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Edward', 'Simpson', '8 Darwin Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Harry', 'Simpson', '4482 Comanche Drive');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Donald', 'Walker', '6888 Reindahl Avenue');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Karen', 'Patterson', '604 Ronald Regan Plaza');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Lois', 'Davis', '2949 Gina Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Harry', 'Montgomery', '282 Coolidge Drive');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Sharon', 'Ford', '6396 Pankratz Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Antonio', 'Robertson', '110 Melvin Plaza');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Lillian', 'Harvey', '128 Grover Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'George', 'Chavez', '0 7th Court');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Henry', 'Wilson', '8 Amoth Court');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Susan', 'Lopez', '0 Hagan Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Dorothy', 'Chapman', '18 Roth Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Tammy', 'Duncan', '70 Lerdahl Avenue');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Gary', 'Bennett', '0835 Nobel Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Martha', 'Porter', '56 Becker Parkway');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Alice', 'Black', '3698 Calypso Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Stephanie', 'Murphy', '5891 Killdeer Parkway');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Jean', 'Daniels', '724 Buell Road');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'James', 'Rivera', '33598 Prairieview Way');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Willie', 'Simpson', '497 Miller Place');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kathleen', 'King', '6942 Meadow Vale Place');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kathleen', 'Mccoy', '7 Lerdahl Parkway');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Russell', 'Thomas', '2295 Glacier Hill Point');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Roger', 'Hunter', '63788 Eastwood Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kathryn', 'Russell', '40331 Barby Avenue');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Patrick', 'Hughes', '76183 Lighthouse Bay Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Cheryl', 'Willis', '15 Maple Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Louis', 'Shaw', '86459 Bay Lane');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Michael', 'Ward', '21447 Mariners Cove Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Jean', 'Miller', '39800 Russell Park');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kenneth', 'Wood', '77128 Clove Hill');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Jason', 'Morales', '7960 Morning Hill');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Jean', 'James', '5657 Sloan Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Phyllis', 'Andrews', '4227 Artisan Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Angela', 'Wright', '6 Evergreen Court');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Tina', 'Burke', '7373 Truax Center');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Nicholas', 'Morales', '51887 Linden Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Teresa', 'Burns', '33502 Ilene Road');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Douglas', 'Larson', '1131 Briar Crest Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Douglas', 'Roberts', '7 Village Alley');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Jonathan', 'Diaz', '4 Sullivan Hill');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Carol', 'Fox', '9 Reindahl Avenue');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Norma', 'Hunter', '46 Victoria Court');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Sean', 'Sullivan', '00333 Hermina Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Robert', 'White', '02660 Paget Court');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kathleen', 'Clark', '3 Spohn Alley');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Ernest', 'Little', '6 Lunder Court');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Louis', 'Carr', '34547 Miller Center');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Patrick', 'Garza', '46967 Hoard Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kathy', 'Fernandez', '7 Anderson Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Joe', 'Murphy', '72 Fisk Road');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Brandon', 'Ford', '9722 Gale Way');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Raymond', 'Griffin', '171 Merchant Plaza');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Joyce', 'Jackson', '10 Lakewood Drive');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Susan', 'Reed', '7 Corben Parkway');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Wanda', 'Ellis', '948 Calypso Center');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Judy', 'Payne', '98356 Sutteridge Parkway');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Charles', 'Cox', '99 Orin Hill');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Sean', 'Montgomery', '5341 Holmberg Drive');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Jonathan', 'Day', '41376 Stang Alley');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Kathryn', 'Garcia', '9 Logan Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Benjamin', 'Banks', '07 Chinook Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Louise', 'Anderson', '06 Hallows Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Terry', 'Matthews', '68879 Rusk Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Terry', 'Armstrong', '03384 Oak Valley Alley');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Emily', 'Gordon', '10 Alpine Drive');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Stephanie', 'Perez', '9380 Alpine Park');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Ruth', 'Clark', '790 Walton Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Sandra', 'Olson', '6347 Golden Leaf Alley');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Janice', 'Harris', '46 Artisan Way');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Judith', 'Adams', '61 Dapin Road');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Beverly', 'Bailey', '6537 Meadow Valley Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Ruby', 'Stephens', '17625 Meadow Valley Pass');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Theresa', 'Fisher', '9153 Service Drive');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Judith', 'Fox', '177 Di Loreto Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Lori', 'Bowman', '223 Bashford Circle');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Richard', 'Powell', '3785 Schmedeman Crossing');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Jeffrey', 'Reyes', '59129 Esker Way');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Melissa', 'Green', '917 Norway Maple Court');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Larry', 'Alexander', '61 Roth Avenue');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Virginia', 'Davis', '870 Village Green Lane');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Earl', 'Robertson', '42 School Terrace');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Philip', 'Nichols', '458 Carioca Center');
insert into animal_keeper (id, name, surname, address) values (nextval('animal_keeper_id_seq'), 'Margaret', 'Jenkins', '90 Lotheville Road');