insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Andzelika', 'Kliencka', '22-222 Klientowo ul. Kliencka 123');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Katherine', 'Hughes', '38815 Porter Pass');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Maria', 'Simmons', '478 Loeprich Plaza');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Kathryn', 'Cooper', '836 Miller Parkway');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Carlos', 'Rice', '58132 Ruskin Court');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Frank', 'Fields', '726 Susan Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Paul', 'Stone', '29 Maple Wood Road');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Lori', 'Hawkins', '309 Independence Pass');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Keith', 'Austin', '6687 Carey Terrace');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Juan', 'Gutierrez', '70734 Kinsman Pass');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Donald', 'Thompson', '7332 Memorial Junction');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Frank', 'Patterson', '95449 Scott Street');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Dennis', 'Fisher', '7061 Del Sol Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Bobby', 'Wheeler', '35383 Green Ridge Parkway');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Earl', 'Rivera', '285 Lakeland Terrace');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Roy', 'Moore', '1489 Dennis Way');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Mark', 'Cook', '8010 Amoth Park');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Joyce', 'Roberts', '26945 Sherman Hill');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Nicholas', 'Gonzalez', '992 Westridge Place');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Kathy', 'Hernandez', '05854 Northfield Hill');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Chris', 'Ortiz', '49 Summit Point');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Kimberly', 'Marshall', '13060 Fordem Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Wanda', 'Jackson', '29458 Sachs Road');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Richard', 'Duncan', '303 Melvin Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jacqueline', 'Woods', '31 Grayhawk Center');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Mary', 'Gonzales', '950 Kim Circle');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Anna', 'Meyer', '44 Debs Pass');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Michael', 'Porter', '6176 Loftsgordon Circle');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Roy', 'Garrett', '05796 Eagle Crest Trail');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Douglas', 'Edwards', '3300 Laurel Road');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Victor', 'Wright', '23 Cody Park');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Martha', 'Griffin', '04 Algoma Trail');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Douglas', 'Murray', '95899 Old Gate Plaza');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'David', 'Morris', '04 Elmside Alley');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Phyllis', 'Harris', '302 Oak Valley Place');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jeffrey', 'Jenkins', '6936 Bunting Circle');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Pamela', 'Ellis', '45 Truax Street');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Paula', 'Davis', '26803 Graedel Park');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Christine', 'Nelson', '6015 Oak Court');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Walter', 'Chavez', '7796 Summit Lane');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Christina', 'Lawrence', '76046 Bay Trail');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Alice', 'Gordon', '9 7th Point');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jennifer', 'Schmidt', '108 Artisan Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Roger', 'Gordon', '401 Kennedy Street');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jacqueline', 'Garza', '8 Tomscot Plaza');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Katherine', 'Mills', '54360 Ramsey Avenue');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Helen', 'Ruiz', '8 Old Shore Avenue');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jose', 'Gonzales', '08 Continental Way');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Frances', 'Freeman', '72758 Independence Hill');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Karen', 'Lawson', '25499 Dottie Park');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Joan', 'Mitchell', '01 Lindbergh Plaza');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Doris', 'Hall', '61712 Nobel Parkway');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Phillip', 'Berry', '3 Derek Road');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Nicole', 'Mcdonald', '98897 Comanche Park');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Adam', 'Russell', '78 Springview Center');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Judy', 'Fuller', '2743 Prairie Rose Trail');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Bobby', 'Spencer', '33 Division Court');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Tina', 'Ford', '94 Ramsey Way');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Randy', 'Jordan', '3096 Katie Center');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Marie', 'Nguyen', '0 Oak Avenue');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Earl', 'Crawford', '7540 Sommers Alley');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Michael', 'Anderson', '7 Hanson Avenue');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Joyce', 'Hill', '0434 Mosinee Trail');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Benjamin', 'Miller', '9 Leroy Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Samuel', 'Phillips', '4271 Portage Place');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Andrew', 'Hamilton', '82 Village Green Lane');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Theresa', 'Parker', '1 Sugar Terrace');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Marilyn', 'Crawford', '92773 Hudson Hill');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Albert', 'Wells', '13 Namekagon Plaza');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Willie', 'Murray', '8 Merry Parkway');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Doris', 'Fisher', '992 Oneill Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Linda', 'Hart', '42694 Glacier Hill Circle');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Louise', 'Harris', '1 Brentwood Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jimmy', 'Peters', '6597 Lighthouse Bay Hill');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Keith', 'Wright', '92 Nancy Center');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Melissa', 'Lawson', '33345 Stoughton Pass');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Lori', 'Morrison', '701 Moland Terrace');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Pamela', 'Pierce', '504 Sugar Drive');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Martin', 'Grant', '84 Victoria Crossing');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jeffrey', 'Rivera', '251 Nelson Trail');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Paul', 'Hernandez', '5295 Scoville Park');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Anna', 'Torres', '4 Elka Alley');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Dennis', 'Gibson', '754 Rockefeller Circle');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Maria', 'Frazier', '35 Clove Center');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Robin', 'Wallace', '71 Gulseth Plaza');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Adam', 'Bell', '60764 Shopko Pass');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Ronald', 'Cole', '32735 Village Green Center');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Harry', 'Harvey', '92267 Pankratz Junction');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Irene', 'Fowler', '3 Vera Road');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Helen', 'Ford', '017 Hoepker Terrace');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Ralph', 'Myers', '3 Ridgeway Road');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Timothy', 'Thompson', '09595 Bay Court');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Todd', 'Martinez', '1 Emmet Park');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Maria', 'Fernandez', '8 Kedzie Hill');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Jason', 'Davis', '17965 Kings Alley');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Katherine', 'Reid', '77 Butterfield Plaza');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Fred', 'Alvarez', '0 Swallow Way');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Michelle', 'Cruz', '9355 Lakeland Parkway');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Patricia', 'Ross', '6935 Tomscot Lane');
insert into client (id, name, surname, address) values (nextval('client_id_seq'), 'Katherine', 'Medina', '3 Duke Way');