-- Generated by Oracle SQL Developer Data Modeler 4.1.5.907
--   at:        2016-12-08 14:27:54 CET
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c




CREATE TABLE administrator
  (
    id      INTEGER NOT NULL ,
    name    VARCHAR (256) NOT NULL ,
    surname VARCHAR (256) NOT NULL ,
    address VARCHAR (512) NOT NULL
  ) ;
ALTER TABLE administrator ADD CONSTRAINT administrator_PK PRIMARY KEY ( id ) ;

CREATE TABLE article
  (
    id      VARCHAR (64) NOT NULL ,
    title    VARCHAR (256) NOT NULL ,
    content  TEXT NOT NULL
  ) ;
ALTER TABLE article ADD CONSTRAINT article_PK PRIMARY KEY ( id ) ;

CREATE TABLE animal
  (
    registration_number INTEGER NOT NULL ,
    name                VARCHAR (128) NOT NULL ,
    age                 INTEGER NOT NULL ,
    sex                 VARCHAR (32) NOT NULL ,
    species             VARCHAR (64) NOT NULL ,
    link_to_image       VARCHAR (256) ,
    room_number         INTEGER NOT NULL ,
    adoption_possible   INTEGER NOT NULL ,
    acceptance_date     TIMESTAMP NOT NULL ,
    adoption_date       TIMESTAMP
  ) ;
ALTER TABLE animal ADD CONSTRAINT animal_PK PRIMARY KEY ( registration_number ) ;


CREATE TABLE animal_keeper
  (
    id      INTEGER NOT NULL ,
    name    VARCHAR (256) NOT NULL ,
    surname VARCHAR (256) NOT NULL ,
    address VARCHAR (512) NOT NULL
  ) ;
ALTER TABLE animal_keeper ADD CONSTRAINT animal_keeper_PK PRIMARY KEY ( id ) ;


CREATE TABLE app_user
  (
    login            VARCHAR (128) NOT NULL ,
    password         VARCHAR (256) NOT NULL ,
    e_mail           VARCHAR (128) NOT NULL ,
    is_active        INTEGER NOT NULL ,
    user_role        VARCHAR (64) NOT NULL ,
    client_id        INTEGER ,
    vet_id           INTEGER ,
    animal_keeper_id INTEGER ,
    administrator_id INTEGER
  ) ;
ALTER TABLE app_user ADD CONSTRAINT App_user_PK PRIMARY KEY ( login ) ;


CREATE TABLE application
  (
    id            INTEGER NOT NULL ,
    dispatch_date TIMESTAMP NOT NULL ,
    status        VARCHAR (32) NOT NULL ,
    client_id     INTEGER NOT NULL ,
    animal_id    INTEGER NOT NULL
  ) ;
ALTER TABLE application ADD CONSTRAINT application_PK PRIMARY KEY ( id ) ;


CREATE TABLE client
  (
    id      INTEGER NOT NULL ,
    name    VARCHAR (256) NOT NULL ,
    surname VARCHAR (256) NOT NULL ,
    address VARCHAR (512) NOT NULL
  ) ;
ALTER TABLE client ADD CONSTRAINT client_PK PRIMARY KEY ( id ) ;


CREATE TABLE donation
  (
    id            INTEGER NOT NULL ,
    amount        FLOAT NOT NULL ,
    donation_date TIMESTAMP NOT NULL ,
    client_id     INTEGER NOT NULL
  ) ;
ALTER TABLE donation ADD CONSTRAINT payment_PK PRIMARY KEY ( id ) ;


CREATE TABLE food_rations
  (
    id           INTEGER NOT NULL ,
    amount       INTEGER NOT NULL ,
    warehouse_id INTEGER NOT NULL ,
    animal_id    INTEGER NOT NULL
  ) ;
ALTER TABLE food_rations ADD CONSTRAINT food_rations_PK PRIMARY KEY ( id ) ;


CREATE TABLE medical_card
  (
    id           INTEGER NOT NULL ,
    health_state VARCHAR (32) NOT NULL ,
    notes        VARCHAR (512) ,
    animal_id    INTEGER NOT NULL
  ) ;
ALTER TABLE medical_card ADD CONSTRAINT medical_card_PK PRIMARY KEY ( id ) ;


CREATE TABLE medical_treatment
  (
    id              INTEGER NOT NULL ,
    name            VARCHAR (64) NOT NULL ,
    description     VARCHAR (256) ,
    importance      INTEGER NOT NULL ,
    start_date      TIMESTAMP NOT NULL ,
    end_date        TIMESTAMP ,
    medical_card_id INTEGER NOT NULL
  ) ;
ALTER TABLE medical_treatment ADD CONSTRAINT medical_treatment_PK PRIMARY KEY ( id ) ;


CREATE TABLE vet
  (
    id      INTEGER NOT NULL ,
    name    VARCHAR (256) NOT NULL ,
    surname VARCHAR (256) NOT NULL ,
    address VARCHAR (512) NOT NULL
  ) ;
ALTER TABLE vet ADD CONSTRAINT vet_PK PRIMARY KEY ( id ) ;


CREATE TABLE warehouse
  (
    id         INTEGER NOT NULL ,
    amout_left INTEGER NOT NULL ,
    capacity   INTEGER NOT NULL
  ) ;
ALTER TABLE warehouse ADD CONSTRAINT Warehouse_PK PRIMARY KEY ( id ) ;


ALTER TABLE app_user ADD CONSTRAINT App_user_administrator_FK FOREIGN KEY ( administrator_id ) REFERENCES administrator ( id ) ;

ALTER TABLE app_user ADD CONSTRAINT App_user_animal_keeper_FK FOREIGN KEY ( animal_keeper_id ) REFERENCES animal_keeper ( id ) ;

ALTER TABLE app_user ADD CONSTRAINT App_user_client_FK FOREIGN KEY ( client_id ) REFERENCES client ( id ) ;

ALTER TABLE app_user ADD CONSTRAINT App_user_vet_FK FOREIGN KEY ( vet_id ) REFERENCES vet ( id ) ;

ALTER TABLE application ADD CONSTRAINT application_client_FK FOREIGN KEY ( client_id ) REFERENCES client ( id ) ;

ALTER TABLE application ADD CONSTRAINT application_client_FK FOREIGN KEY ( animal_id ) REFERENCES animal ( registration_number ) ;

ALTER TABLE donation ADD CONSTRAINT donation_client_FK FOREIGN KEY ( client_id ) REFERENCES client ( id ) ;

ALTER TABLE food_rations ADD CONSTRAINT food_rations_animal_FK FOREIGN KEY ( animal_id ) REFERENCES animal ( registration_number ) ;

ALTER TABLE medical_card ADD CONSTRAINT medical_card_animal_FK FOREIGN KEY ( animal_id ) REFERENCES animal ( registration_number ) ;

ALTER TABLE medical_treatment ADD CONSTRAINT treatment_medical_card_FK FOREIGN KEY ( medical_card_id ) REFERENCES medical_card ( id ) ;

ALTER TABLE food_rations ADD CONSTRAINT warehouse_FK FOREIGN KEY ( warehouse_id ) REFERENCES warehouse ( id ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
